module.exports={
  configureWebpack:{
    resolve:{
      alias:{
        'common':'@/common',
        'components':'@/components',
        'assets':'@/assets',
        'views':'@/views',
        'network':'@/network'
      }
    }
  }
}